### PR TITLE
add CS and link from Actor definitions, cleanup copyright

### LINKED ISSUE #88: add Capability Statements

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #88

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
Given that the CS didn't exist before, I did not auto approve this PR. Committee should review before approval.

Once approved, committee should consider if this should be released as a patch release. It provides something useful, but does not change any requirements.

**Comment by JohnMoehrke** [comment]
http://build.fhir.org/ig/IHE/ITI.PDQm/branches/moehrke-cs/index.html

**Comment by JohnMoehrke** [comment]
The CS did exist before, there was no references to them. The actor names were not right, so I prefer to keep the new definitions. The description on the old ones were better. The definitions were identical.  So updating the PR to remove the old definitions and adjust the new CS descriptions.

**Review by lukeaduncan — APPROVED** [review]
Added address to the search parameters.

Was the copyright removed on purpose from the sushi-config?

**Comment by JohnMoehrke** [comment]
Yes the copyright should not be in the sushi config as it comes by way of the template. the explicit listing in the sushi config causes a replication of the copyright statement in a way that is not helpful and only appears on the first page.

**Pull request merged**
